CREATE TABLE [dbo].[TaskActivities] (
    [Id]                INT              IDENTITY (1, 1) NOT NULL,
    [TaskGroupId]       INT              NOT NULL,
    [Sequence]          INT              NOT NULL,
    [TaskWeekId]        INT              NOT NULL,
    [MondayStatusId]    INT              DEFAULT ((1)) NOT NULL,
    [TuesdayStatusId]   INT              DEFAULT ((1)) NOT NULL,
    [WednesdayStatusId] INT              DEFAULT ((1)) NOT NULL,
    [ThursdayStatusId]  INT              DEFAULT ((1)) NOT NULL,
    [FridayStatusId]    INT              DEFAULT ((1)) NOT NULL,
    [SaturdayStatusId]  INT              DEFAULT ((1)) NOT NULL,
    [SundayStatusId]    INT              DEFAULT ((1)) NOT NULL,
    [TaskDefinitionId]  INT              NOT NULL,
    [UserIdentifier]    UNIQUEIDENTIFIER NULL,
    [AccountId]         INT              NULL,
    PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_TaskActivities_ToAccount (Id)] FOREIGN KEY ([AccountId]) REFERENCES [dbo].[Accounts] ([Id]),
    CONSTRAINT [FK_TaskActivities_ToActivityStatus_Friday] FOREIGN KEY ([FridayStatusId]) REFERENCES [dbo].[ActivityStatus] ([Id]),
    CONSTRAINT [FK_TaskActivities_ToActivityStatus_Monday] FOREIGN KEY ([MondayStatusId]) REFERENCES [dbo].[ActivityStatus] ([Id]),
    CONSTRAINT [FK_TaskActivities_ToActivityStatus_Saturday] FOREIGN KEY ([SaturdayStatusId]) REFERENCES [dbo].[ActivityStatus] ([Id]),
    CONSTRAINT [FK_TaskActivities_ToActivityStatus_Sunday] FOREIGN KEY ([SundayStatusId]) REFERENCES [dbo].[ActivityStatus] ([Id]),
    CONSTRAINT [FK_TaskActivities_ToActivityStatus_Thursday] FOREIGN KEY ([ThursdayStatusId]) REFERENCES [dbo].[ActivityStatus] ([Id]),
    CONSTRAINT [FK_TaskActivities_ToActivityStatus_Tuesday] FOREIGN KEY ([TuesdayStatusId]) REFERENCES [dbo].[ActivityStatus] ([Id]),
    CONSTRAINT [FK_TaskActivities_ToActivityStatus_Wednesday] FOREIGN KEY ([WednesdayStatusId]) REFERENCES [dbo].[ActivityStatus] ([Id]),
    CONSTRAINT [FK_TaskActivities_ToTaskDefinitions (Id)] FOREIGN KEY ([TaskDefinitionId]) REFERENCES [dbo].[TaskDefinitions] ([Id]),
    CONSTRAINT [FK_TaskActivities_ToTaskGroups] FOREIGN KEY ([TaskGroupId]) REFERENCES [dbo].[TaskGroups] ([Id]),
    CONSTRAINT [FK_TaskActivities_ToTaskWeeks] FOREIGN KEY ([TaskWeekId]) REFERENCES [dbo].[TaskWeeks] ([Id])
);

